language: php
php:
      - 5.5
install: npm install
before_script:
      - npm update -g npm
      - npm install grunt-cli
      - sudo apt-get update
      - sudo apt-get install apache2 libapache2-mod-fastcgi
      # enable php-fpm
      - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
      - sudo a2enmod rewrite actions fastcgi alias
      - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
      # configure apache virtual hosts
      - sudo cp -f travis-ci-apache /etc/apache2/sites-available/default
      - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
      - sudo service apache2 restart
      - mysql -e "create database IF NOT EXISTS ospos;" -uroot
      - mysql -e "use ospos; source database/database.sql;" -uroot
      - cp application/config/database.php.tmpl application/config/database.php
script: grunt mochaWebdriver:test
