sudo: required
dist: trusty
group: deprecated-2017Q4
branches:
  except:
    - weblate
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - date=`date +%Y%m%d%H%M%S` && branch=${TRAVIS_BRANCH} && rev=`git rev-parse --short=6
    HEAD` && sed -i "s/\$1/\$1.$date.$branch.$rev/g" deployment.json
script:
  - docker run --rm -v $(pwd):/app jekkos/composer composer install
  - docker run --rm -v $(pwd):/app jekkos/composer php bin/install.php translations develop
  - sed -i "s/'\(dev\)'/'$rev'/g" application/config/config.php
  - docker run --rm -it -v $(pwd):/app -w /app digitallyseamless/nodejs-bower-grunt
    sh -c "npm install && bower install && grunt package"
  - docker-compose build
  - docker-compose -f docker-compose.test.yml up --abort-on-container-exit
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.21.1 
    - TAG=$(echo ${TRAVIS_BRANCH} | sed s/feature\\///)
after_success: 
  - 'docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker tag "opensourcepos_ospos:latest" "jekkos/opensourcepos:$TAG" && docker push "jekkos/opensourcepos:$TAG"'
deploy:
  file: deployment.json
  provider: bintray
  skip_cleanup: true
  key: ${BINTRAY_API_KEY}
  user: jekkos
  on:
    all_branches: true
