title: Opensourcepos
description: Open Source Point of Sale is a web based point of sale system written in the PHP language. It uses MySQL as the data storage back-end and has a simple user interface.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
