include:
  - docker/docker-mysql.yml

services:
    sqlscript:
        image: jekkos/opensourcepos:sqlscript
        command: /bin/sh -c 'exit 0'
    ospos:
        image: jekkos/opensourcepos:master
        restart: always
        depends_on:
          - mysql
        ports:
          - "127.0.0.1:80:80"
        networks:
          - app_net
        volumes:
          - uploads:/app/public/uploads
          - logs:/app/application/logs
        environment:
          - CI_ENVIRONMENT=production
          - FORCE_HTTPS=false
          - PHP_TIMEZONE=UTC
          - MYSQL_USERNAME=admin
          - MYSQL_PASSWORD=pointofsale
          - MYSQL_DB_NAME=ospos
          - MYSQL_HOST_NAME=mysql

