version: '2'

volumes:
    uploads:
        driver: local

networks:
    ospos_net:

services:
    sqlscript:
        build:
            context: database/
            dockerfile: Dockerfile

    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - ospos_net
        volumes:
            - uploads:/app/public/uploads
        environment:
            - FORCE_HTTPS=false
            - PHP_TIMEZONE=UTC
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql

    mysql:
        image: mariadb:10.3.9
        ports:
            - "3306:3306"
        networks:
            - ospos_net
        volumes_from:
            - sqlscript
        environment:
            - MYSQL_ROOT_PASSWORD=pointofsale
            - MYSQL_DATABASE=ospos
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=pointofsale

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        restart: always
#        ports:
#           - "8000:80"
#        networks:
#            - ospos_net
#        environment:
#            - MYSQL_USERNAME=admin
#            - MYSQL_ROOT_PASSWORD=pointofsale
#            - PMA_HOST=mysql
